# Generated by Django 5.0.4 on 2025-01-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_patient"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
    ]
