# Generated by Django 5.0.4 on 2025-01-04 16:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0004_service_bill_billservice"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
