# Generated by Django 5.0.4 on 2025-01-10 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0010_delete_appointment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Allergy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("Mild", "Mild"),
                            ("Moderate", "Moderate"),
                            ("Severe", "Severe"),
                        ],
                        max_length=20,
                    ),
                ),
                ("symptoms", models.TextField()),
                ("diagnosis_date", models.DateField()),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allergies",
                        to="pages.patient",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Allergies",
                "ordering": ["-diagnosis_date"],
            },
        ),
        migrations.CreateModel(
            name="ChronicCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("Mild", "Mild"),
                            ("Moderate", "Moderate"),
                            ("Severe", "Severe"),
                        ],
                        max_length=20,
                    ),
                ),
                ("diagnosis_date", models.DateField()),
                ("treatment_plan", models.TextField()),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chronic_conditions",
                        to="pages.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-diagnosis_date"],
            },
        ),
        migrations.CreateModel(
            name="InheritedIllness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("relation", models.CharField(max_length=50)),
                ("diagnosis_date", models.DateField()),
                ("treatment", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inherited_illnesses",
                        to="pages.patient",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Inherited Illnesses",
                "ordering": ["-diagnosis_date"],
            },
        ),
        migrations.CreateModel(
            name="ProgressNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("description", models.TextField()),
                ("treatment", models.TextField(blank=True, null=True)),
                ("prescription", models.TextField(blank=True, null=True)),
                ("next_appointment", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="progress_notes",
                        to="pages.user",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_notes",
                        to="pages.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
