# Generated by Django 5.0.4 on 2025-01-11 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0011_allergy_chroniccondition_inheritedillness_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                ("report_id", models.AutoField(primary_key=True, serialize=False)),
                ("date_generated", models.DateField()),
                ("description", models.TextField()),
                (
                    "generated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.user"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.patient"
                    ),
                ),
            ],
        ),
    ]
